### PR TITLE
created html for bmi and food, updated variables in javascript code, …

### PR DESCRIPTION
**Pull request by KaChunWuGary**
…ensured javascript functionality for second row which includes food input, created two separate local storage functions for BMI to FOOD

### CODE REVIEW

**Review by rapostoljr — APPROVED** [review]

**Comment by dahfefe** [comment]
Javascript looks great!

**Comment by gaganjitV** [comment]
Reviewed the code.

**Comment by KaChunWuGary** [comment]
This is Romulo's and Felix's code

**Review by rapostoljr — COMMENTED** [review]
Code looks good!

**Review by gaganjitV — APPROVED** [review]
Looks good!

**Review by dahfefe — APPROVED** [review]

**Review by sagagi74 — APPROVED** [review]
nice job

**Pull request merged**
